# Generated by Django 3.2.6 on 2021-08-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_rpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Mini4wds', 'mini4wd'), ('Motors', 'motor'), ('Hubs', 'hub'), ('Racing Circuits', 'circuit')], max_length=50),
        ),
    ]
