# Generated by Django 3.2.6 on 2021-08-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Mini4wds', 'Mini4wds'), ('Motors', 'Motors'), ('Hubs', 'Hubs'), ('Racing Circuits', 'Racing Circuits')], max_length=50),
        ),
    ]
